language: cpp
compiler: gcc

before_install:
  - git submodule update --init --recursive > /dev/null
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install:
  - sudo apt-get install -qq autoconf automake m4 gcc-4.9 g++-4.9
  - git clone https://github.com/OpenStratos/WiringPi.git > /dev/null
  - ./WiringPi/build

script:
  - "bash -ex ./build.sh"

branches:
  only:
    - master
    - develop
    - /^feature\/.+$/
    - /^release\/.+$/
    - /^hotfix\/.+$/

notifications:
  email:
    recipients:
      - iban.eguia@opendeusto.es
      - jordan.aranda@me.com
      - aritzbilbao@deusto.es
      - eneko.cruz@opendeusto.es
    on_success: change
    on_failure: always
