language: cpp
script:
  - aclocal
  - autoheader
  - automake --add-missing
  - autoconf
  - ./configure
  - make utesting
  - ./utesting
compiler: gcc

sudo: false
branches:
only:
- master
- develop
- /^feature\/.+$/
- /^release\/.+$/
- /^hotfix\/.+$/