language: cpp
compiler: gcc

before_install:
  - git submodule update --init --recursive > /dev/null
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  - autoconf --version

install:
  - sudo apt-get install -qq autoconf automake m4 gnulib gcc-4.9 g++-4.9
  - "bash -ex ./install-wiringpi.sh"

script:
  - "bash -ex ./build.sh"

branches:
  only:
    - master
    - develop
    - /^feature\/.+$/
    - /^release\/.+$/
    - /^hotfix\/.+$/

notifications:
  email:
    recipients:
      - iban.eguia@opendeusto.es
      - jordan.aranda@me.com
      - aritzbilbao@deusto.es
      - eneko.cruz@opendeusto.es
    on_success: change
    on_failure: always
